### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Phionamary**

### CODE REVIEW

**Comment by Ivankivu** [comment]
Good work!

**Comment by Phionamary** [comment]
Dear,
I think you are supposed to leave the comment in the comment section.
Thank you tho

**Comment by okellogabrielinnocent** [comment]
Good commit messages

**Comment by walimike** [comment]
Thumbs up

**Comment by okellogabrielinnocent** [comment]
Your good to merge your work with master

**Review by okellogabrielinnocent — APPROVED** [review]

**Comment by kyakusahmed** [comment]
good work miss 'P'

**Comment by KicaRonaldOkello** [comment]
It is good work, but I think your commit messages should be descriptive. It should sound sort of like a command and also be in present tense.

**Comment by HKiwooma** [comment]
It looks OK but how try attach a link to your pivotal story

**Pull request merged**
